name: Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question? Ask away! For general discussions, consider using [GitHub Discussions](../../discussions).

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...? / Why does...? / Can you explain...?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      options:
        - Algorithm Implementation
        - Using the Application
        - Contributing/Development
        - Technical Details
        - Educational Content
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any relevant details or what you've already tried
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked the README and documentation
          required: true
        - label: I have searched existing issues
          required: true
